version: '2'
checks:
  method-complexity:
    config:
      threshold: 9
exclude_patterns:
  - ".yarn/**"
  - ".vscode/**"
  - ".github/**"
  - "docs/**"
plugins:
  eslint:
    enabled: true
    config: .eslintrc.js
    channel: eslint-7
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
        - TODO
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 90
