name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn run lint
  test:
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2

        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --immutable
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: yarn run test
          coverageLocations: |
            ${{github.workspace}}/coverage/*.lcov:lcov
